clear all

% Load Model file for RUSTree
modelPath="R:\ASommer\Matlab\Models\model_pilo_bilateral_27FEB26_used_14MAY26.mat";
model = load(modelPath);

% Fs of raw data
Fs=20000;
% Fs of downsampled data
dFs=1250;
% n Channels used to score data 
nChannel = length(model.ops.ch_subj);
% freq range of wavelet transform
freq = model.ops.freqs;
nFreq = length(freq);
% size of output feature vector
feat = nan(1,nFreq*nChannel);

% reassign to modelOPs to match closedLoop scripts
modelOPs.freqs = freq;
modelOPs.durFeat = model.ops.durFeat; % 4s feature bins
modelOPs.art_thres = 5e4; % NOTE probably needs to be decreased
modelOPs.features = model.ops.features;
modelOPs.ch_subj = model.ops.ch_subj;
modelOPs.Fs = dFs; % The Fs assigned to modelOPs is the Fs used for 
                   % wavelet transformation, and must match that of 
                   % input data



%% Load data for one epoch to test

time=0;
v.sessiondata.xml.nChannels=16;

folder="R:\ASommer\PilocarpineRecordings\PTP_Opto\Baseline\5-13-2026(10.59)\RHD_260513_110031\";
amp="amplifier.dat";
datpath=[folder+amp];
data = LoadBinary(datpath,'nchannels',v.sessiondata.xml.nChannels,'frequency', ...
    Fs,'channels',modelOPs.ch_subj,'duration', modelOPs.durFeat,'start',time);


amp="amplifier.lfp";
datpath=[folder+amp];
lfp_data = LoadBinary(datpath,'nchannels',v.sessiondata.xml.nChannels,'frequency', ...
    dFs,'channels',modelOPs.ch_subj,'duration', modelOPs.durFeat,'start',time);


folder="R:\ASommer\PilocarpineRecordings\PTP_Opto\Baseline\5-13-2026(10.59)\"
amp="amplifier_16Ch_1.25KHz_int16.dat";
datpath=[folder+amp];
saved_data = LoadBinary(datpath,'nchannels',v.sessiondata.xml.nChannels,'frequency', ...
    dFs,'channels',modelOPs.ch_subj,'duration', modelOPs.durFeat,'start',time);

%% Plot if desired

figure
plot(data)

figure
plot(lfp_data)
%% Test various downsampling schema

%%%%
% Test scoring on non-downsampled data
% And time it
modelOPs.Fs = 20000;

t1=datetime('now');

feats = modelOPs.features(data,[],modelOPs);
[label,conf] = predict(model.rusTree,feats);

t20k=second(datetime('now'))-second(t1);


%%%%
% Test scoring on separately-loaded LFP data
% Reassign modelOPs.Fs to dFs
modelOPs.Fs = dFs;

t1=datetime('now');

lfp_feats = modelOPs.features(lfp_data,[],modelOPs);
[lfp_label,lfp_conf] = predict(model.rusTree,lfp_feats);

tlfp=second(datetime('now'))-second(t1);

%%%%
% Test scoring on LFP data generated by subsampling
t1=datetime('now');

dataT=data';
lfp_ds_data = dataT(:,1:round(Fs/dFs):end)';
lfp_ds_feats = modelOPs.features(lfp_ds_data,[],modelOPs);
[lfp_ds_label, lfp_ds_conf] = predict(model.rusTree,lfp_ds_feats);

tlfp_ds=second(datetime('now'))-second(t1);

%%%%
% Test scoring on LFP data generated by convLFP function
t1=datetime('now');

lfp_convds_data=[];
for channel =1:size(data,2);
    lfp_convds_data(:,channel)=convLPFilttest(double(data(:,channel)),dFs/2,Fs,[],Fs/dFs)';
end
lfp_convds_feats = modelOPs.features(lfp_convds_data,[],modelOPs);
[lfp_convds_label,lfp_convds_conf] = predict(model.rusTree,lfp_convds_feats);

tconvds=second(datetime('now'))-second(t1);

%%%%
% Test scoring on LFP data generated by lowpass then downsample functions
t1=datetime('now');

filtdata=[];
lfp_lpds_data=[];

filtdata=lowpass(double(data),modelOPs.Fs/2,20000);
lfp_lpds_data=downsample(filtdata,Fs/dFs);
lfp_lpds_feats = modelOPs.features(lfp_lpds_data,[],modelOPs);
[lfp_lpds_label,lfp_lpds_conf] = predict(model.rusTree,lfp_lpds_feats);
tlpds=second(datetime('now'))-second(t1);

%%%%
% Test scoring on LFP data generated by decimate function
t1=datetime('now');

filtdata=[];
for channel =1:size(data,2)
    filtdata(:,channel) = decimate(double(data(:,channel)),Fs/dFs);
end
lfp_dec_data=filtdata;
lfp_dec_feats = modelOPs.features(lfp_dec_data,[],modelOPs);
[lfp_dec_label,lfp_dec_conf] = predict(model.rusTree,lfp_dec_feats);
tdec=second(datetime('now'))-second(t1);


%%%%
% Test scoring on LFP data generated by decimate function
t1=datetime('now');

saved_feats = modelOPs.features(saved_data,[],modelOPs);
[saved_label,saved_conf] = predict(model.rusTree,saved_feats);
tsaved=second(datetime('now'))-second(t1);


%%
figure
plot(feats)
hold on
plot(lfp_feats)
plot(lfp_ds_feats)
plot(lfp_convds_feats)
plot(lfp_lpds_feats)
plot(lfp_dec_feats)
plot(saved_feats)


disp(['20kHz label: ',num2str(label)])
disp(['.LFP label: ',num2str(lfp_label)])
disp(['RT DS option 1 label: ',num2str(lfp_ds_label)])
disp(['RT DS w Filt label: ',num2str(lfp_convds_label)])
disp(['LP then DS label: ',num2str(lfp_lpds_label)])
disp(['Decimate label: ',num2str(lfp_dec_label)])
disp(['Saved label: ',num2str(saved_label)])


disp(['20kHz conf: ',9,num2str(conf)])
disp(['.LFP conf: ',9,9,num2str(lfp_conf)])
disp(['RT DS option 1 conf: ',9,num2str(lfp_ds_conf)])
disp(['RT DS w Filt conf: ',9,num2str(lfp_convds_conf)])
disp(['LP then DS conf: ',9,num2str(lfp_lpds_conf)])
disp(['Saved conf: ',9,num2str(saved_conf)])


pdist2(feats,lfp_feats,"Euclidean")
pdist2(lfp_feats,lfp_ds_feats,"Euclidean")
pdist2(lfp_feats,lfp_convds_feats,"Euclidean")
pdist2(lfp_feats,lfp_lpds_feats,"Euclidean")
pdist2(lfp_feats,lfp_dec_feats,"Euclidean")


%%